title: Den Shin's Blog
description: "Den's Blog"
author:
  name: "Shin Yeong Hyeon"
  email: "den.shin.dev@gmail.com"
  url: ""

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

# 댓글
comments:
  provider: "disqus"
  disqus:
    shortname: "shinyeonghyeon-github-io"
disqus_shortname: "shinyeonghyeon-github-io"
disqus_url: "shinyeonghyeon-github-io.disqus.com"
disqus_id: "shinyeonghyeon-github-io"


defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Shin Yeong Hyeon"
year : "2020"

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/shinYeongHyeon"

